name: scyard
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
  - r
dependencies:
  - numpy=1.26.4
  - pillow=10.4.0
  - pip=24.2
  - python=3.9.20
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - tensorboard=2.17.0
  - wheel=0.44.0
  - pip:
      - gym==0.26.2
      - gymnasium==0.29.1
      - learn2learn==0.2.0
      - pettingzoo==1.24.3
      - scipy==1.13.1
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchvision==0.19.1
      - wandb==0.18.3